name: kafdrop

image:
  registry: quay.io
  repository: justindav1s
  name: kafdrop
  version: latest

deploy:
  kafka: true

config:
  loglevel: INFO
  kafka:
    cluster:
      domain: kafka-bootstrap-events.apps.sno.openshiftlabs.net
      name: kafka
    user: app-user
    kafdrop:
     user: kafdrop-kafka-user


