name: kafdrop

image:
  registry: quay.io
  repository: justindav1s
  name: kafdrop
  version: latest

deploy:
  kafka: false

config:
  loglevel: INFO
  kafka:
    cluster:
      domain: kafka-bootstrap-kafdrop.apps.sno.openshiftlabs.net
      name: test-cluster
    user: kafdrop-kafka-user


