---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      name: {{ .Values.name }}
      labels:
        app: {{ .Values.name }}
      annotations:
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: oauth-proxy
          image: openshift/oauth-proxy:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: {{ .Values.name }}-oauth-proxy-tls
            mountPath: /etc/pki/tls/private 
          ports:
          - containerPort: 8443
            name: public
          args:
          - --https-address=:8443
          - --provider=openshift
          - --openshift-service-account={{ .Values.name }}
          - --upstream=http://0.0.0.0:9000
          - --cookie-secret=QWERTYUY
          - --tls-cert=/etc/pki/tls/private/tls.crt
          - --tls-key=/etc/pki/tls/private/tls.key
          - --ssl-insecure-skip-verify=true
        - resources:
            limits:
              cpu: '400m'
              memory: 1Gi
            requests:
              cpu: '200m'
              memory: 512Mi
          name: quarkus
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: prometheus
              containerPort: 9779
              protocol: TCP
            - name: jolokia
              containerPort: 8778
              protocol: TCP
          imagePullPolicy: Always
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.version }}
          volumeMounts:
          - name: {{ .Values.name }}-kafka-properties
            mountPath: /deployments/config
          - name: {{ .Values.name }}-application-yaml
            mountPath: /deployments/resources
          - name: sim-reg-user-keystore
            mountPath: /deployments/keystore            
          - name: wc-test-kafka-cluster-truststore
            mountPath: /deployments/truststore
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: {{ .Values.name }}-application-yaml
          configMap:
            name: {{ .Values.name }}-application-yaml
        - name: {{ .Values.name }}-kafka-properties
          secret:
            secretName: {{ .Values.name }}-kafka-properties
        - name: {{ .Values.config.kafka.user }}-keystore
          secret:
            secretName: {{ .Values.config.kafka.user }}
        - name: {{ .Values.config.kafka.cluster.name }}-truststore
          secret:
            secretName: {{ .Values.config.kafka.cluster.name }}-truststore 
        - name: {{ .Values.name }}-oauth-proxy-tls
          secret:
            secretName: {{ .Values.name }}-oauth-proxy-tls
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
