apiVersion: v1
data:
  kafka.properties: |-
    bootstrap.servers={{ .Values.config.kafka.cluster.name }}-{{ .Values.config.kafka.cluster.domain }}:443
    security.protocol=SSL
    ssl.truststore.location=truststore/ca.p12
    ssl.truststore.type=PKCS12
    ssl.keystore.location=keystore/user.p12
    ssl.keystore.type=PKCS12
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Values.name }}-kafka-properties
