kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ingress-to-{{ .Values.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: openshift-ingress
  policyTypes:
    - Ingress