kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  annotations:
spec:
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  port:
    targetPort: 8443
  tls:
    termination: Reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None