---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    expose: 'true'
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ .Values.name }}-oauth-proxy-tls
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8443
  type: ClusterIP
  selector:
    app: {{ .Values.name }}